name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test Scala
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java (for sbt)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup sbt
        uses: actions/setup-scala@v1
        with:
          sbt-version: 1.9.6 
      - name: Cache sbt and Ivy
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-cache-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            sbt-cache-${{ runner.os }}-

      - name: Compile frontend
        run: sbt frontend/fullOptJS

      - name: Compile backend
        run: sbt backend/compile

      - name: Run tests
        run: sbt test
